### ISSUE TITLE
[Alpine] pinns.c:153:11: error: implicit declaration of function 'TEMP_FAILURE_RETRY'

### ISSUE THREAD

**Issue by AkihiroSuda** [cri-o/cri-o#4136]
**Description**

pinns can't be compiled on Alpine, because glibc extension TEMP_FAILURE_RETRY isn't supported on Alpine's musl libc.

Regression in ad2ed3b792

**Steps to reproduce the issue:**

Build the following Dockerfile:
```dockerfile
FROM golang:1.15-alpine3.12
RUN apk -q --no-cache add bash build-base git linux-headers libseccomp-dev
RUN git clone -q https://github.com/cri-o/cri-o.git /go/src/github.com/cri-o/cri-o
WORKDIR /go/src/github.com/cri-o/cri-o
# 2020-08-28T19:43:30Z
ARG CRIO_COMMIT=be9e42b7010803346df24c374d98c50de1ae7d29
RUN git pull && git checkout ${CRIO_COMMIT}
RUN make bin/pinns
```

**Describe the results you received:**

```console
$ docker build -t foo .
[+] Building 3.7s (9/9) FINISHED                                                                                       
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 38B                                                                               0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/golang:1.15-alpine3.12                                         3.2s
 => [1/6] FROM docker.io/library/golang:1.15-alpine3.12@sha256:73182a0a24a1534e31ad9cc9e3a4bb46bb030a883b26eda0a  0.0s
 => CACHED [2/6] RUN apk -q --no-cache add bash build-base git linux-headers libseccomp-dev                       0.0s
 => CACHED [3/6] RUN git clone -q https://github.com/cri-o/cri-o.git /go/src/github.com/cri-o/cri-o               0.0s
 => CACHED [4/6] WORKDIR /go/src/github.com/cri-o/cri-o                                                           0.0s
 => CACHED [5/6] RUN git pull && git checkout be9e42b7010803346df24c374d98c50de1ae7d29                            0.0s
 => ERROR [6/6] RUN make bin/pinns                                                                                0.5s
------                                                                                                                 
 > [6/6] RUN make bin/pinns:                                                                                           
#9 0.322 make -C pinns                                                                                                 
#9 0.324 make[1]: Entering directory '/go/src/github.com/cri-o/cri-o/pinns'                                            
#9 0.324 cc -std=c99 -Os -Wall -Werror -Wextra -static   -c -o pinns.o pinns.c                                         
#9 0.344 pinns.c: In function 'main':                                                                                  
#9 0.344 pinns.c:153:11: error: implicit declaration of function 'TEMP_FAILURE_RETRY' [-Werror=implicit-function-declaration]
#9 0.344   153 |       if (TEMP_FAILURE_RETRY(write(p[1], "0", 1)) < 0)
#9 0.344       |           ^~~~~~~~~~~~~~~~~~
#9 0.406 cc1: all warnings being treated as errors
#9 0.407 make[1]: *** [<builtin>: pinns.o] Error 1
#9 0.407 make[1]: Leaving directory '/go/src/github.com/cri-o/cri-o/pinns'
#9 0.408 make: *** [Makefile:161: bin/pinns] Error 2
------
executor failed running [/bin/sh -c make bin/pinns]: runc did not terminate successfully
```

**Describe the results you expected:**

Shouldn't fail
