### PR TITLE
[1.11 backport] RunAsGroup fixes

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

> /kind bug

#### What this PR does / why we need it:

This is a backport of PR #2091 (which itself is a backport of PRs #1898 and #2090) to 1.11 branch, fixing supplementary container user groups.

#### Which issue(s) this PR fixes:

Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1782105

#### Does this PR introduce a user-facing change?

```release-note
Fix supplementary container user groups
```

### CODE REVIEW

**Comment by haircommander** [comment]
```
../../containerd/release-tool/vendor/github.com/urfave/cli/v2/fish.go:74:18: undefined: strings.Builder

../../containerd/release-tool/vendor/github.com/urfave/cli/v2/fish.go:123:18: undefined: strings.Builder

../../containerd/release-tool/vendor/github.com/urfave/cli/v2/fish.go:160:45: undefined: strings.Builder

Makefile:201: recipe for target '.install.release' failed

make: *** [.install.release] Error 2

The command "make install.tools" failed and exited with 2 during .
```
interesting, I don't think that was there before...

**Comment by kolyshkin** [comment]
strings.Builder is only available in go 1.10+, I guess we're using an older version :(

**Comment by kolyshkin** [comment]
> I don't think that was there before

Indeed it was passing with Go 1.9 before, see e.g. https://github.com/cri-o/cri-o/runs/915241867

But since we're using containerd/release-tool without pinning it to a specific version:

 Makefile:               go get -u github.com/containerd/release-tool; \

it very well might fail.

Let me try to fix this

**Comment by kolyshkin** [comment]
> ../../containerd/release-tool/vendor/github.com/urfave/cli/v2/fish.go:160:45: undefined: strings.Builder

Caused by https://github.com/containerd/release-tool/pull/16

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming the tests get happy

**Comment by kolyshkin** [comment]
/test e2e_crun

(others, I guess, are expected to fail)

**Comment by kolyshkin** [comment]
cgroupv2 failures are expected I guess
