### PR TITLE
[1.31][4.18] OCPBUGS-59416: HighPerformanceHooks: Fix IRQ SMP affinity race conditions

### PR DESCRIPTION
**Pull request by andreaskaris**
cherry-pick of https://github.com/cri-o/cri-o/pull/9350

#### Special notes for your reviewer:

The same as for the change to `main`, I ran a smoke test for sanity checking:

I ran my smoke test on a VM with 14 CPUs where I first installed the entire stack with kubeadm.

Dependencies:
```
# rpm -qa | grep kubelet
kubelet-1.33.1-150500.1.1.x86_64
# rpm -qa | grep kubeadm
kubeadm-1.33.1-150500.1.1.x86_64
# rpm -qa | grep crun
crun-1.21-1.el9.x86_64
# rpm -qa | grep conmon
conmon-2.1.13-1.el9.x86_64
```

/etc/crio/crio.conf.d/99-runtimes.conf
```
[crio.runtime]
infra_ctr_cpuset = "0-3"




# The CRI-O will check the allowed_annotations under the runtime handler and apply high-performance hooks when one of
# high-performance annotations presents under it.
# We should provide the runtime_path because we need to inform that we want to re-use runc binary and we
# do not have high-performance binary under the $PATH that will point to it.
[crio.runtime.runtimes.high-performance]
inherit_default_runtime = true
allowed_annotations = ["cpu-load-balancing.crio.io", "cpu-quota.crio.io", "irq-load-balancing.crio.io", "cpu-c-states.crio.io", "cpu-freq-governor.crio.io"]
```

```
# tail -n 5 /var/lib/kubelet/config.yaml
cpuManagerPolicy: static
cpuManagerPolicyOptions:
  full-pcpus-only: "true"
cpuManagerReconcilePeriod: 5s
reservedSystemCPUs: 0-3
```

I then stopped the crio service, started the compiled crio in foreground `make binaries && bin/crio`, and ran this smoke test:

smoke.sh
```
#!/bin/bash

set -x

affinity_file="/proc/irq/default_smp_affinity"
expected_reset_affinity="3fff"
expected_mask="3e0f"

echo $expected_reset_affinity > $affinity_file
cat $affinity_file

for i in {0..20}; do
	set +x
	echo "========"
	echo "Run ${i}"
	echo "========"
	set -x
	kubectl apply -f pod.yaml
	kubectl wait --for=condition=Ready pod/qos-demo --timeout=180s
	mask=$(cat ${affinity_file} | tr -d '\n')
        echo "Got mask: $mask, expected mask: $expected_mask"
        if [ "${mask}" != "${expected_mask}" ]; then
            exit 1
        fi
        kubectl delete pod qos-demo
        kubectl wait --for=delete pod/qos-demo --timeout=180s
	mask=$(cat ${affinity_file} | tr -d '\n')
	echo "After reset --- Got mask: $mask, expected mask: $expected_reset_affinity"
	if [ "${mask}" != "${expected_reset_affinity}" ]; then
	    exit 1
	fi
done
```

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  annotations:
    irq-load-balancing.crio.io: "disable"
spec:
  hostNetwork: true
  runtimeClassName: performance-performance
  containers:
  - name: qos-demo-ctr-1
    image: quay.io/akaris/nice-test
    command:
    - "/bin/sleep"
    - "infinity"
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "1"
  - name: qos-demo-ctr-2
    image: quay.io/akaris/nice-test
    command:
    - "/bin/sleep"
    - "infinity"
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "1"
  - name: qos-demo-ctr-3
    image: quay.io/akaris/nice-test
    command:
    - "/bin/sleep"
    - "infinity"
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "1"
  - name: qos-demo-ctr-4
    image: quay.io/akaris/nice-test
    command:
    - "/bin/sleep"
    - "infinity"
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "1"
  - name: qos-demo-ctr-5
    image: quay.io/akaris/nice-test
    command:
    - "/bin/sleep"
    - "infinity"
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "1"
```

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by andreaskaris** [comment]
To do: Have to fix conflict in unit test due to missing:
https://github.com/cri-o/cri-o/commit/4409a15f667612b44eb8cf4f7c7b220ac647bd84#diff-bc25e15e13072e3a8ff7fc6a28ab46835c3051e5dca571380e110210c1edabae

```

3m 12s
Run golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
prepare environment
run golangci-lint
  Running [/home/runner/golangci-lint-1.60.3-linux-amd64/golangci-lint run] in [/home/runner/work/cri-o/cri-o] ...
  internal/runtimehandlerhooks/default_cpu_load_balance_hooks_linux.go:1: : # github.com/cri-o/cri-o/internal/runtimehandlerhooks [github.com/cri-o/cri-o/internal/runtimehandlerhooks.test]
  Error: internal/runtimehandlerhooks/high_performance_hooks_test.go:803:20: undefined: sandbox.NewBuilder (typecheck)
  package runtimehandlerhooks
  
  Error: issues found
  Ran golangci-lint in 191263ms
```

**Comment by andreaskaris** [comment]
Note: AFAICT, BSD didn't build on 1.31 even before this patch, due to missing 3ef54986886f0df5570f9b33ec493ba480a7524b which removed GetRuntimeHandlerHooks.
